/* ============================================================
   Atos Societários · Totali
   modelos-coop.js — ESTATUTO SOCIAL de cooperativa, transcrito
   dos modelos oficiais publicados pela JUCESE (DREI):
     • ESTATUTO-SOCIAL-DE-COOPERATIVA (Lei nº 5.764/1971)
     • ESTATUTO-SOCIAL-DA-COOPERATIVA-DE-TRABALHO (Lei nº 12.690/2012)

   REGRA DESTE ARQUIVO: o texto é o do modelo, palavra por palavra.
   O que o modelo deixa em branco vira {{campo}}; o que o modelo
   oferece como "OU" vira uma escolha ("opc") — e nada é inventado.
   Cooperativa é sociedade de pessoas com regras próprias (voto por
   cabeça, fundos indivisíveis, quotas intransferíveis a terceiros):
   uma cláusula "melhorada" de cabeça pode ferir a Lei 5.764 e a
   Junta devolve. Se algum dia for preciso mudar redação, mudar
   AQUI, com o modelo ao lado.

   Estrutura: lista de blocos. Cada bloco é
     {tit:"TÍTULO I", sub:"..."}      cabeçalho de título
     {cap:"CAPÍTULO I", sub:"..."}    cabeçalho de capítulo
     {sec:"SEÇÃO I", sub:"..."}       cabeçalho de seção
     {art:"1º", txt:"...", inc:[...], al:[...], par:[...]}
   onde inc = incisos (I, II, III…), al = alíneas (a, b, c…) e
   par = parágrafos ("§ 1º …" ou "Parágrafo único. …").
   Um bloco pode ter "opc" = nome da escolha e "quando" = valor
   que a ativa; blocos sem "opc" entram sempre.
   ============================================================ */
(function () {
  "use strict";

  /* ---------- ESTATUTO DE COOPERATIVA (Lei nº 5.764/1971) ---------- */
  var GERAL = [
    { tit: "TÍTULO I", sub: "DAS DISPOSIÇÕES INICIAIS" },
    { cap: "CAPÍTULO I", sub: "DA DENOMINAÇÃO, SEDE, FORO, PRAZO DE DURAÇÃO, ÁREA DE AÇÃO E EXERCÍCIO SOCIAL" },
    { art: "1º", txt: "A {{denominacao}}, constituída em {{dataConstituicao}}, de acordo com a Ata de Assembleia Geral de Constituição, neste Estatuto Social designada simplesmente de Cooperativa, sociedade de pessoas, sem fins lucrativos, rege-se pelos princípios do cooperativismo, por este Estatuto Social e pela legislação vigente, tendo:",
      al: [
        "sede, administração e foro jurídico em {{sede}}, na cidade de {{cidade}}, {{uf}};",
        "área de admissão de associados, abrangendo {{areaAdmissao}}, podendo atuar em todo o território nacional;",
        { opc: "prazo", quando: "indeterminado", txt: "prazo de duração indeterminado e exercício social com duração de doze meses, com início em 1º de janeiro e término em 31 de dezembro de cada ano." },
        { opc: "prazo", quando: "determinado", txt: "prazo de duração até {{prazoFim}} e exercício social com duração de {{exercicioMeses}} meses, com início em {{exercicioInicio}} e término em {{exercicioFim}} de cada ano." }
      ] },
    { cap: "CAPÍTULO II", sub: "DO OBJETO SOCIAL" },
    { art: "2º", txt: "A Cooperativa, com base na colaboração recíproca a que se obrigam seus associados, se caracteriza pela prestação direta de serviços aos associados e tem por objeto social {{objeto}}.",
      par: ["Parágrafo único. Em todos os aspectos das atividades executadas na Cooperativa devem ser rigorosamente observados os princípios da neutralidade política e da não discriminação religiosa, racial, social ou de gênero."] },
    { tit: "TÍTULO II", sub: "DOS ASSOCIADOS" },
    { cap: "CAPÍTULO I", sub: "DAS CONDIÇÕES DE ADMISSÃO" },
    { opc: "admissao", quando: "livre", art: "3º", txt: "Podem se associar à Cooperativa todos que desejarem utilizar os serviços prestados pela sociedade, desde que adiram aos propósitos sociais e preencham as condições estabelecidas neste Estatuto, salvo se houver impossibilidade técnica de prestação de serviços pela Cooperativa.",
      par: ["§ 1º Poderão ingressar na Cooperativa, excepcionalmente, pessoas jurídicas que tenham por objeto as mesmas ou correlatas atividades econômicas das pessoas físicas ou, ainda, aquelas sem fins lucrativos, desde que satisfaçam as condições estabelecidas neste Estatuto Social.",
            "§ 2º Não podem ingressar no quadro da Cooperativa os agentes de comércio e empresários que operem no mesmo campo econômico da sociedade.",
            "§ 3º A representação da pessoa jurídica junto à Cooperativa se fará por meio de pessoa física especialmente designada, mediante instrumento específico que, nos casos em que houver mais de um representante, identificará os poderes de cada um."] },
    { opc: "admissao", quando: "restrita", art: "3º", txt: "Podem se associar à Cooperativa {{admissaoQuem}}, salvo se houver impossibilidade técnica de prestação de serviços pela Cooperativa.",
      par: ["§ 1º Poderão ingressar na Cooperativa, excepcionalmente, pessoas jurídicas que tenham por objeto as mesmas ou correlatas atividades econômicas das pessoas físicas ou, ainda, aquelas sem fins lucrativos, desde que satisfaçam as condições estabelecidas neste Estatuto Social.",
            "§ 2º Não podem ingressar no quadro da Cooperativa os agentes de comércio e empresários que operem no mesmo campo econômico da sociedade.",
            "§ 3º A representação da pessoa jurídica junto à Cooperativa se fará por meio de pessoa física especialmente designada, mediante instrumento específico que, nos casos em que houver mais de um representante, identificará os poderes de cada um."] },
    { art: "4º", txt: "O número de associados será ilimitado quanto ao máximo, não podendo ser inferior a vinte pessoas físicas." },
    { art: "5º", txt: "Para adquirir a qualidade de associado, o interessado deverá ter a sua admissão aprovada pelo órgão de administração da Cooperativa, subscrever as quotas-partes na forma prevista neste Estatuto Social, assinar o Livro de Matrícula e outros documentos necessários para a efetivação da associação.",
      par: ["Parágrafo único. Cumprido o que dispõe o caput deste artigo, o associado adquire todos os direitos e assume todos os deveres decorrentes da lei, deste Estatuto Social e das deliberações tomadas pela Assembleia Geral."] },
    { cap: "CAPÍTULO II", sub: "DOS DIREITOS" },
    { art: "6º", txt: "São direitos do associado:",
      inc: ["ser convocado para as Assembleias Gerais, discutir e votar os assuntos que nelas forem tratados, ressalvadas as disposições legais e estatutárias;",
            "ser votado para os cargos sociais, desde que atendidas as disposições legais e regulamentares pertinentes;",
            "participar de todas as atividades que constituam o objeto da Cooperativa;",
            "propor medidas que julgar convenientes aos interesses da Cooperativa;",
            "examinar, mediante pedido formal prévio, informações e documentos relativos às atividades, aos negócios e à administração da Cooperativa;",
            "receber devolução do capital integralizado, juros e sobras, nos termos deste Estatuto Social;",
            "tomar conhecimento dos normativos da Cooperativa;",
            "demitir-se da Cooperativa quando lhe convier, obedecidas as disposições aplicáveis deste Estatuto Social."],
      par: ["Parágrafo único. A fim de serem apreciadas pela Assembleia Geral, as propostas dos associados, referidas neste Estatuto, deverão ser previamente apresentadas ao órgão de administração e constar do respectivo Edital de Convocação."] },
    { cap: "CAPÍTULO III", sub: "DOS DEVERES" },
    { art: "7º", txt: "São deveres dos associados:",
      inc: ["satisfazer, pontualmente, os compromissos que contrair com a Cooperativa;",
            "realizar com a Cooperativa as operações econômicas que constituam sua finalidade;",
            "integralizar as quotas-partes do capital subscritas, nos termos deste Estatuto Social;",
            "cobrir as perdas do exercício, quando houver, proporcionalmente às operações que realizou com a Cooperativa, se o Fundo de Reserva não for suficiente para cobri-las;",
            "arcar, na proporção direta da fruição de serviços prestados pela Cooperativa, com a cobertura das despesas da sociedade, bem como das taxas de serviço e encargos operacionais que forem estabelecidos;",
            "cumprir as disposições da lei e deste Estatuto Social, as deliberações das Assembleias Gerais, do órgão de administração{{,daDiretoriaExecutiva}}, bem como de outros instrumentos de normatização destinados direta ou indiretamente aos associados;",
            "zelar pelos interesses morais, éticos, sociais e materiais da Cooperativa;",
            "prestar, quando solicitado, esclarecimentos sobre as suas atividades à Cooperativa;",
            "manter suas informações cadastrais atualizadas junto à Cooperativa;",
            "comunicar, sem a necessidade de se identificar, situações com indícios de ilicitude de qualquer natureza, relacionadas à Cooperativa; e",
            "participar das Assembleias Gerais, discutir e votar os assuntos que nelas forem tratados, ressalvadas as disposições legais e estatutárias."] },
    { cap: "CAPÍTULO IV", sub: "DAS HIPÓTESES DE DESLIGAMENTO DE ASSOCIADOS" },
    { sec: "SEÇÃO I", sub: "DA DEMISSÃO" },
    { art: "8º", txt: "A demissão do associado dar-se-á unicamente a seu pedido e será formalizada mediante termo firmado no Livro de Matrícula.",
      par: ["§ 1º O órgão de administração será comunicado sobre os pedidos de demissão em sua primeira reunião subsequente à data de protocolo dos pedidos.",
            "§ 2º A data da demissão do associado será a data do protocolo do pedido de demissão na Cooperativa."] },
    { sec: "SEÇÃO II", sub: "DA ELIMINAÇÃO" },
    { art: "9º", txt: "A eliminação do associado, que se efetivará mediante termo firmado por quem de direito no Livro de Matrícula, será aplicada em virtude de infração legal ou estatutária, ou ainda quando:",
      inc: ["exercer qualquer atividade considerada prejudicial à Cooperativa;",
            "praticar atos que, a critério da Cooperativa, a desabonem, como emissão de cheques sem fundos em qualquer instituição financeira, inclusão nos sistemas de proteção ao crédito, pendências registradas no Banco Central do Brasil, atrasos constantes e relevantes em operações de crédito e operações baixadas em prejuízo na Cooperativa;",
            "deixar de honrar qualquer compromisso perante a Cooperativa, ou perante terceiro, no qual a Cooperativa tenha prestado qualquer espécie de garantia pela qual ela seja obrigada a honrar em decorrência da inadimplência do associado;",
            "estiver divulgando entre os demais associados e/ou perante a comunidade a prática de falsas irregularidades na Cooperativa ou violar sigilo de operação ou de serviço prestado pela Cooperativa;",
            "exercer qualquer atividade que conflite com o objeto social da Cooperativa;",
            "deixar de cumprir as obrigações por ele contratadas na Cooperativa;",
            "deixar de realizar com a Cooperativa as operações que constituem seu objeto social; e",
            "deixar de integralizar o capital dentro do prazo previsto neste Estatuto."] },
    { art: "10", txt: "A eliminação do associado será decidida e registrada em ata de reunião do órgão de administração.",
      par: ["§ 1º O associado será notificado no prazo de trinta dias, contados da data da reunião em que se deliberou a eliminação, por instrumento que descreva os motivos que a determinaram e comprove a data da notificação.",
            "§ 2º O associado eliminado terá direito a interpor recurso, com efeito suspensivo, no prazo de {{prazoRecurso}}, a contar da notificação, o qual será analisado pela primeira Assembleia Geral posterior.",
            "§ 3º A eliminação do associado será formalizada mediante termo firmado no Livro de Matrícula."] },
    { sec: "SEÇÃO III", sub: "DA EXCLUSÃO" },
    { art: "11", txt: "A exclusão do associado será feita nos seguintes casos:",
      inc: ["dissolução da pessoa jurídica;", "morte da pessoa física;", "incapacidade civil não suprida; ou", "deixar de atender aos requisitos estatutários de ingresso ou permanência na Cooperativa."],
      par: ["§ 1º A exclusão do associado será formalizada mediante termo firmado no Livro de Matrícula.",
            "§ 2º A exclusão com fundamento no inciso IV será efetivada por decisão do órgão de administração, com os motivos que a determinaram, observadas as regras para eliminação de associados."] },
    { sec: "SEÇÃO IV", sub: "DISPOSIÇÕES GERAIS" },
    { art: "12", txt: "Em qualquer caso de demissão, eliminação ou exclusão, o associado só terá direito à restituição do capital integralizado, das sobras e de outros créditos que lhe tiverem sido registrados.",
      par: ["§ 1º A restituição de que trata este artigo somente poderá ser exigida depois de aprovado, pela Assembleia Geral, o balanço do exercício em que o associado tenha sido desligado da Cooperativa.",
            "§ 2º O órgão de administração da Cooperativa poderá determinar que a restituição deste capital seja feita em parcelas, a partir do exercício financeiro que se seguir àquele em que se deu o desligamento e no mesmo prazo e condições da integralização.",
            "§ 3º Os atos de demissão, eliminação ou exclusão acarretam o vencimento e pronta exigibilidade das dívidas do associado com a Cooperativa, sobre cuja liquidação caberá ao órgão de administração decidir.",
            "§ 4º Ocorrendo demissões, eliminações ou exclusões de associados em número tal que as restituições das importâncias referidas neste artigo possam ameaçar a estabilidade econômico-financeira da Cooperativa, esta poderá restituí-las mediante critérios que resguardem a sua continuidade."] },
    { cap: "CAPÍTULO V", sub: "DAS RESPONSABILIDADES" },
    { opc: "responsabilidade", quando: "limitada", art: "13", txt: "O associado responde pelos compromissos da Cooperativa limitado ao valor do capital por ele subscrito e o montante das perdas que lhe couber.",
      par: ["Parágrafo único. A responsabilidade do associado para com terceiros, como membro da sociedade, somente poderá ser invocada depois de judicialmente exigida da Cooperativa."] },
    { opc: "responsabilidade", quando: "ilimitada", art: "13", txt: "O associado responde por todos os compromissos da Cooperativa, de forma pessoal, solidária e independente do valor do capital por ele subscrito.",
      par: ["Parágrafo único. A responsabilidade do associado para com terceiros, como membro da sociedade, somente poderá ser invocada depois de judicialmente exigida da Cooperativa."] },
    { art: "14", txt: "A responsabilidade do associado perante terceiros, por compromissos da sociedade, perdura para os demitidos, eliminados ou excluídos até quando aprovadas as contas do exercício em que se deu o desligamento.",
      par: ["Parágrafo único. As obrigações dos associados falecidos, contraídas com a sociedade, e as oriundas de sua responsabilidade como associado em face de terceiros, passam aos herdeiros, prescrevendo, porém, após um ano contado do dia da abertura da sucessão, ressalvados os casos previstos em lei."] },
    { tit: "TÍTULO III", sub: "DO CAPITAL SOCIAL" },
    { art: "15", txt: "O capital social da Cooperativa é ilimitado quanto ao máximo e variará conforme o número de quotas-partes subscritas, não podendo ser inferior a {{capitalMinimo}} ({{capitalMinimoExt}}).",
      par: ["§ 1º O capital é dividido em quotas-partes de valor unitário igual a {{valorQuota}} ({{valorQuotaExt}}) cada uma.",
            "§ 2º A quota-parte é indivisível, intransferível a não associados, não podendo ser negociada de modo algum, nem dada em garantia, e todo o seu movimento de subscrição, integralização, transferência e restituição será sempre escriturado no Livro de Matrícula.",
            "§ 3º A transferência de quotas-partes entre associados, total ou parcial, será escriturada no Livro de Matrícula, mediante termo que contenha as assinaturas do cedente, do cessionário e do dirigente que o Estatuto designar.",
            "§ 4º O associado deve integralizar as quotas-partes à vista ou em parcelas periódicas, devendo o órgão de administração estabelecer o número e dia de vencimento para pagamento das parcelas.",
            "§ 5º A integralização de quotas-partes e o aumento do capital social poderão ser feitos com bens previamente avaliados e após homologação em Assembleia Geral ou mediante retenção de determinada porcentagem do valor do movimento financeiro de cada associado.",
            "§ 6º É vedada a distribuição de qualquer espécie de benefício às quotas-partes do capital ou estabelecer outras vantagens ou privilégios, financeiros ou não, em favor de quaisquer associados ou terceiros.",
            "§ 7º A Cooperativa poderá distribuir juros de até doze por cento ao ano sobre o capital integralizado, se houver sobras, mediante deliberação da Assembleia Geral.",
            "§ 8º O capital social da Cooperativa será calculado pela multiplicação do valor unitário da quota-parte pelo número mínimo de quotas-partes a serem subscritas por cada associado e pelo número mínimo de associados."] },
    { art: "16", txt: "O número de quotas-partes do capital social a ser subscrito pelo associado, por ocasião de sua admissão, não poderá ser inferior a {{minQuotas}} ({{minQuotasExt}}) quotas-partes nem superior a um terço do total do capital social da Cooperativa." },
    { art: "17", txt: "Os herdeiros do associado falecido têm direito ao capital integralizado e demais créditos pertencentes ao mesmo, assegurando-lhes o direito de ingresso na Cooperativa, desde que preencham as condições estabelecidas neste Estatuto, mediante requerimento expresso." },
    { tit: "TÍTULO IV", sub: "DOS ÓRGÃOS SOCIAIS" },
    { cap: "CAPÍTULO I", sub: "DA ASSEMBLEIA GERAL" },
    { art: "18", txt: "A Assembleia Geral é o órgão supremo da Cooperativa, cabendo-lhe tomar toda e qualquer decisão de interesse da sociedade, dentro dos limites da lei e deste Estatuto Social.",
      par: ["Parágrafo único. As decisões tomadas em Assembleia Geral vinculam a todos os associados, ainda que ausentes ou discordantes, e constarão de ata lavrada em livro próprio ou em folhas soltas."] },
    { art: "19", txt: "A Assembleia Geral será habitualmente convocada e dirigida pelo Presidente da Cooperativa.",
      par: ["Parágrafo único. A Assembleia Geral, também, poderá ser convocada por qualquer dos órgãos de administração, pelo Conselho Fiscal, ou após solicitação não atendida, por um quinto dos associados em pleno gozo de seus direitos sociais."] },
    { art: "20", txt: "Em qualquer das hipóteses referidas neste Estatuto, as Assembleias Gerais serão convocadas com antecedência mínima de dez dias, com o horário definido para as três convocações, sendo de no mínimo uma hora o intervalo entre elas." },
    { art: "21", txt: "O quorum para instalação da Assembleia Geral será:",
      inc: ["dois terços do número de associados, em primeira convocação;", "metade mais um dos associados, em segunda convocação; e", "mínimo de dez associados, em terceira convocação."],
      par: ["§ 1º Para efeito de verificação do quorum de que trata este artigo, o número de associados presentes, em cada convocação, será contado por suas assinaturas apostas no Livro de Presença, seguidas do respectivo número de matrícula.",
            "§ 2º Constatada a existência de quorum no horário estabelecido no Edital de Convocação, o Presidente instalará a Assembleia, com a declaração do número de associados presentes, e fará transcrever estes dados para a respectiva ata."] },
    { art: "22", txt: "Não havendo quorum para instalação da Assembleia Geral, será feita nova convocação, com antecedência mínima de dez dias." },
    { art: "23", txt: "Dos editais de convocação das Assembleias Gerais deverão constar:",
      inc: ["a denominação da Cooperativa e o número de Cadastro Nacional de Pessoas Jurídicas – CNPJ, seguidos da expressão “Convocação da Assembleia Geral Ordinária ou Extraordinária”, conforme o caso;",
            "o dia e a hora da reunião, em cada convocação, assim como o local da sua realização, o qual, salvo motivo justificado, será o da sede social;",
            "a sequência ordinal das convocações;",
            "a ordem do dia dos trabalhos, com as devidas especificações e, em caso de reforma do Estatuto Social, a indicação precisa da matéria;",
            "o número de associados existentes na data de sua expedição, para efeito do cálculo do quorum de instalação; e",
            "a data e assinatura do responsável pela convocação."],
      par: ["§ 1º No caso de a convocação ser feita por associados, o edital será assinado, no mínimo, por um quinto dos associados em pleno gozo dos seus direitos.",
            "§ 2º Os editais de convocação serão afixados em locais visíveis das dependências geralmente frequentadas pelos associados, publicados em jornal de circulação local ou regional, e comunicados aos associados por intermédio de circulares."] },
    { art: "24", txt: "É da competência das Assembleias Gerais, ordinárias ou extraordinárias, a destituição dos membros dos órgãos de administração ou fiscalização.",
      par: ["§ 1º Ocorrendo destituição ou renúncia que possam comprometer a regularidade da administração ou fiscalização da Cooperativa, poderá a Assembleia designar administradores e/ou conselheiros fiscais, até a posse dos novos, cuja eleição se efetuará no prazo máximo de trinta dias, contados a partir da vacância do cargo.",
            "§ 2º Nesse mesmo período deverá ser convocada uma Assembleia Geral para eleger novos administradores e/ou conselheiros fiscais, conforme o caso, cujo mandato será o equivalente ao tempo restante do mandato anterior."] },
    { art: "25", txt: "Os trabalhos das Assembleias Gerais serão dirigidos pelo Presidente, auxiliado por um secretário ad hoc.",
      par: ["Parágrafo único. Quando a Assembleia Geral não tiver sido convocada pelo Presidente, os trabalhos serão dirigidos por um associado escolhido na ocasião, e secretariado por outro, convidado por aquele."] },
    { art: "26", txt: "Os membros dos órgãos de administração e fiscalização, como quaisquer outros associados, não poderão votar nas decisões sobre assuntos que a eles se refiram, direta ou indiretamente, dentre os quais os de prestação de contas e fixação do valor dos honorários, gratificações e cédula de presença, mas não ficarão privados de tomar parte nos respectivos debates." },
    { art: "27", txt: "Nas Assembleias Gerais em que forem discutidos os balanços das contas, inclusive o balanço social, o Presidente da Cooperativa, logo após a leitura do Relatório do órgão de administração, das peças contábeis e do parecer do Conselho Fiscal, solicitará ao plenário que indique um associado para coordenar os debates e a votação da matéria.",
      par: ["§ 1º Transmitida a direção dos trabalhos, o Presidente e demais dirigentes do órgão de administração e os conselheiros fiscais deixarão a mesa, permanecendo no recinto, à disposição da Assembleia Geral para os esclarecimentos que lhes forem solicitados.",
            "§ 2º O coordenador indicado escolherá, dentre os associados, um secretário ad hoc para auxiliá-lo na redação das decisões a serem incluídas na ata pelo secretário da Assembleia Geral."] },
    { art: "28", txt: "As deliberações das Assembleias Gerais somente poderão versar sobre assuntos constantes do Edital de Convocação.",
      par: ["Parágrafo único. Os assuntos que não constarem expressamente do Edital de Convocação e os que não satisfizerem as limitações deste artigo somente poderão ser discutidos depois de esgotada a ordem do dia, sendo que sua votação, se a matéria for considerada objeto de decisão, será obrigatoriamente assunto para nova Assembleia Geral."] },
    { art: "29", txt: "O que ocorrer na Assembleia Geral deverá constar de ata circunstanciada, lavrada no livro próprio, aprovada e assinada ao final dos trabalhos." },
    { art: "30", txt: "As deliberações nas Assembleias Gerais serão tomadas por maioria de votos dos associados presentes com direito de votar, tendo cada associado direito a um só voto, qualquer que seja o número de suas quotas-partes.",
      par: ["§ 1º Em regra, a votação será a descoberto, mas a Assembleia Geral poderá optar pelo voto secreto.",
            "§ 2º Não será permitida a representação de associado por meio de mandatário."] },
    { art: "31", txt: "Fica impedido de votar e ser votado nas Assembleias Gerais o associado que:",
      inc: ["tenha sido admitido após sua convocação;",
            "seja ou tenha se tornado empregado da Cooperativa, perdurando este impedimento até a aprovação pela Assembleia Geral das contas do exercício social em que haja ocorrido a rescisão do contrato de trabalho."] },
    { art: "32", txt: "Prescreve em quatro anos a ação para anular as deliberações da Assembleia Geral viciadas de erro, dolo, fraude ou simulação, ou tomadas com violação de lei ou deste Estatuto Social, contado o prazo da data em que a Assembleia Geral tiver sido realizada." },
    { sec: "SEÇÃO I", sub: "DA ASSEMBLEIA GERAL ORDINÁRIA" },
    { art: "33", txt: "A Assembleia Geral Ordinária será realizada obrigatoriamente uma vez por ano, no decorrer dos três primeiros meses após o término do exercício social, e deliberará sobre os seguintes assuntos, que deverão constar da ordem do dia:",
      inc: ["prestação de contas dos órgãos de administração, acompanhada do parecer do Conselho Fiscal, compreendendo: a) relatório da gestão; b) balanço; c) demonstrativo das sobras apuradas ou das perdas decorrentes da insuficiência das contribuições para cobertura das despesas da sociedade e o parecer do Conselho Fiscal; e d) plano de atividades da Cooperativa para o exercício seguinte;",
            "destinação das sobras apuradas ou o rateio das perdas, deduzindo-se, no primeiro caso, as parcelas para os fundos obrigatórios;",
            "eleição e posse dos componentes dos órgãos de administração e de outros órgãos necessários à administração, quando for o caso;",
            "eleição e posse dos componentes do Conselho Fiscal e de outros, quando for o caso;",
            "quando previsto, a fixação do valor dos honorários, gratificações e cédula de presença dos membros dos órgãos de administração e do Conselho Fiscal;",
            "quaisquer assuntos de interesse social, excluídos aqueles de competência exclusiva da Assembleia Geral Extraordinária enumerados neste Estatuto Social."],
      par: ["§ 1º Os membros dos órgãos de administração e fiscalização não poderão participar da votação das matérias referidas nos incisos I (exceto alínea “d”) e V deste artigo.",
            "§ 2º A aprovação do relatório, balanço e contas dos órgãos de administração não desonera seus componentes da responsabilidade por erro, dolo, fraude ou simulação, bem como por infração da lei ou deste Estatuto Social."] },
    { sec: "SEÇÃO II", sub: "DA ASSEMBLEIA GERAL EXTRAORDINÁRIA" },
    { art: "34", txt: "A Assembleia Geral Extraordinária realizar-se-á sempre que necessário, podendo deliberar sobre qualquer assunto de interesse da Cooperativa, desde que mencionado no Edital de Convocação." },
    { art: "35", txt: "É da competência exclusiva da Assembleia Geral Extraordinária deliberar sobre os seguintes assuntos:",
      inc: ["reforma do Estatuto;", "fusão, incorporação ou desmembramento;", "mudança de objeto da sociedade;", "dissolução voluntária da sociedade e nomeação de liquidantes; e", "contas do liquidante."],
      par: ["Parágrafo único. São necessários os votos de dois terços dos associados presentes para tornar válidas as deliberações de que trata este artigo."] },
    { cap: "CAPÍTULO II", sub: "DA ADMINISTRAÇÃO" },
    /* ----- órgão de administração: Conselho de Administração OU Diretoria (mesmo texto, nome trocado) ----- */
    { opc: "orgao", quando: "conselho", sec: "SEÇÃO I", sub: "DO CONSELHO DE ADMINISTRAÇÃO" },
    { opc: "orgao", quando: "diretoria", sec: "SEÇÃO I", sub: "DA DIRETORIA" },
    { art: "36", txt: "{{OOrgao}} é o órgão competente e responsável pela decisão sobre todo e qualquer assunto de ordem econômica e social, de interesse da Cooperativa ou de seus associados, nos termos da lei, deste Estatuto Social e das recomendações da Assembleia Geral." },
    { art: "37", txt: "{{OOrgao}} será compost{{oa}} de {{nOrgao}} ({{nOrgaoExt}}) membros, sendo um Presidente e {{cargosOrgao}}, todos associados no gozo de seus direitos sociais, eleitos pela Assembleia Geral para mandato de {{mandato}} ({{mandatoExt}}) anos, sendo obrigatória, ao término de cada mandato, a renovação de, no mínimo, um terço dos seus componentes.",
      par: ["§ 1º Não podem fazer parte d{{oa}} {{Orgao}}, além das pessoas impedidas por lei, os condenados a pena que vede, ainda que temporariamente, o acesso a cargos públicos; ou por crime falimentar, de prevaricação, peita ou suborno, concussão, peculato, ou contra a economia popular, a fé pública ou a propriedade.",
            "§ 2º Não podem compor {{oa}} mesm{{oa}} {{Orgao}} os parentes entre si até segundo grau, em linha reta ou colateral."] },
    { art: "38", txt: "Os membros d{{oa}} {{Orgao}} serão eleitos pela Assembleia Geral, tomando posse automaticamente quando for divulgado o resultado pela referida Assembleia." },
    { art: "39", txt: "{{OOrgao}} rege-se pelas seguintes normas:",
      inc: ["reúne-se ordinariamente uma vez por mês, e extraordinariamente sempre que necessário, por convocação do Presidente, da maioria d{{oa}} própri{{oa}} {{Orgao}}, ou, ainda, por solicitação do Conselho Fiscal;",
            "delibera validamente com a presença da maioria dos seus membros, estando proibida a representação, sendo as decisões tomadas pela maioria simples de votos dos presentes, reservado ao Presidente o voto de desempate; e",
            "as deliberações serão consignadas em atas circunstanciadas lavradas em livro próprio, lidas, aprovadas e assinadas ao fim dos trabalhos pelos membros d{{oa}} {{Orgao}} presentes."],
      par: ["Parágrafo único. Perderá automaticamente o cargo o membro d{{oa}} {{Orgao}} que, sem justificativa, faltar a {{faltasConsec}} ({{faltasConsecExt}}) reuniões ordinárias consecutivas ou a {{faltasAno}} ({{faltasAnoExt}}) reuniões durante o ano."] },
    { art: "40", txt: "Cabem {{aoA}} {{Orgao}}, dentro dos limites da lei e deste Estatuto Social, as seguintes atribuições:",
      inc: ["propor à Assembleia Geral as políticas e metas para orientação geral das atividades da Cooperativa, apresentando programas de trabalho e orçamento, além de sugerir as medidas a serem tomadas;",
            "programar as operações e serviços, estabelecendo qualidade e fixando quantidades, valores, prazos, taxas, encargos e demais condições necessárias a sua efetivação;",
            "avaliar e providenciar o montante dos recursos financeiros e dos meios necessários ao atendimento das operações e serviços;",
            "estimar previamente a rentabilidade das operações e serviços, bem como a sua viabilidade;",
            "estabelecer as normas para funcionamento da Cooperativa;",
            "elaborar, juntamente com lideranças do quadro social, regimento interno para organização do quadro social, se houver;",
            "estabelecer sanções ou penalidades a serem aplicadas nos casos de violação ou abuso cometidos contra disposições de lei, deste Estatuto Social, ou das regras de relacionamento com a entidade que venham a ser estabelecidas;",
            "deliberar sobre a admissão, eliminação e exclusão de associados e suas implicações;",
            "deliberar sobre a convocação da Assembleia Geral e estabelecer a ordem do dia, quando for o responsável pela sua convocação, considerando as propostas dos associados, nos termos deste Estatuto Social;",
            "estabelecer a estrutura operacional da administração executiva dos negócios, criando cargos, atribuindo funções e fixando normas para a admissão e demissão dos empregados;",
            "fixar as normas disciplinares;",
            "julgar os recursos formulados pelos empregados contra decisões disciplinares;",
            "avaliar a conveniência e fixar o limite de fiança ou seguro de fidelidade para os empregados que manipulam dinheiro ou valores da Cooperativa;",
            "fixar as despesas de administração em orçamento anual que indique a fonte dos recursos para a sua cobertura;",
            "contratar, quando se fizer necessário, um serviço independente de auditoria, conforme disposto no art. 112 da Lei nº 5.764, de 1971;",
            "indicar instituições financeiras nas quais serão feitos negócios e depósitos de numerário, e fixar limite máximo que poderá ser mantido no caixa da Cooperativa;",
            "estabelecer as normas de controle das operações e serviços, verificando, no mínimo, mensalmente o estado econômico-financeiro da Cooperativa, bem como o desenvolvimento das operações e serviços, mediante balancetes e demonstrativos específicos;",
            "estabelecer regras e sanções para o relacionamento mantido com outras entidades;",
            "contrair obrigações, transigir, adquirir, alienar e onerar bens móveis, ceder direitos e constituir mandatários;",
            "fixar anualmente taxas destinadas a cobrir depreciação ou desgaste dos valores que compõem o ativo permanente da sociedade;",
            "zelar pelo cumprimento da legislação cooperativista e de outras aplicáveis, bem como pelo atendimento da legislação trabalhista e fiscal."],
      par: ["§ 1º O Presidente da Cooperativa providenciará para que os demais membros d{{oa}} {{Orgao}} recebam, com a antecedência mínima de {{diasDocs}} ({{diasDocsExt}}) dias, cópias dos balancetes e demonstrativos, planos e projetos e outros documentos sobre os quais tenham que se pronunciar, sendo-lhes facultado, ainda, anteriormente à reunião correspondente, inquirir empregados ou associados, pesquisar documentos, a fim de dirimir as dúvidas eventualmente existentes.",
            "§ 2º {{OOrgao}} solicitará, sempre que julgar conveniente, o assessoramento de quaisquer funcionários graduados para auxiliá-l{{oa}} no esclarecimento dos assuntos a decidir, podendo determinar que qualquer deles apresente, previamente, projetos sobre questões específicas.",
            "§ 3º As normas estabelecidas pel{{oa}} {{Orgao}} serão baixadas em forma de Resoluções, Regulamentos ou Instruções que, em seu conjunto, constituirão o Regimento Interno da Cooperativa."] },
    { art: "41", txt: "Competem ao Presidente, dentre outros, os seguintes poderes e atribuições:",
      inc: ["dirigir e supervisionar todas as atividades da Cooperativa;",
            "baixar os atos de execução das decisões d{{oa}} {{Orgao}};",
            "assinar, juntamente com outro {{dirigente}} designado pel{{oa}} {{Orgao}}, cheques, contratos e demais documentos constitutivos de obrigações;",
            "convocar e presidir as reuniões d{{oa}} {{Orgao}}, bem como as Assembleias Gerais;",
            "apresentar os balanços e balancetes mensais {{aoA}} {{Orgao}} e ao Conselho Fiscal para apreciação;",
            "apresentar à Assembleia Geral Ordinária: a) relatório da gestão; b) balanço geral; c) demonstrativo das sobras apuradas ou das perdas verificadas no exercício; e d) parecer do Conselho Fiscal;",
            "representar ativa e passivamente a Cooperativa, em juízo e fora dele;",
            "elaborar o plano anual de atividades da Cooperativa;",
            "verificar periodicamente o fluxo financeiro da Cooperativa;",
            "prestar informações verbais ou escritas {{aoA}} {{Orgao}} e ao Conselho Fiscal sobre a situação financeira da Cooperativa, permitindo o livre exame dos livros e documentos;",
            "responsabilizar-se pelos valores e títulos de qualquer natureza pertencentes à Cooperativa."] },
    { art: "42", txt: "Os administradores, eleitos ou contratados, não serão pessoalmente responsáveis pelas obrigações que contraírem em nome da Cooperativa, mas responderão solidariamente pelos prejuízos resultantes de desídia e omissão ou se agiram com culpa, dolo ou má-fé.",
      par: ["§ 1º A Cooperativa responderá pelos atos a que se refere este artigo, se os houver ratificado ou deles logrado proveito.",
            "§ 2º Os que participarem de ato ou operação social em que se oculte a natureza da sociedade podem ser declarados pessoalmente responsáveis pelas obrigações em nome dela contraídas, sem prejuízo das sanções penais cabíveis.",
            "§ 3º O membro d{{oa}} {{Orgao}} que, em qualquer operação, tenha interesse oposto ao da Cooperativa, não poderá participar das deliberações relacionadas com essa operação, cumprindo-lhe declarar seu impedimento.",
            "§ 4º Os componentes d{{oa}} {{Orgao}}, do Conselho Fiscal, bem como os liquidantes, equiparam-se aos administradores das sociedades anônimas para efeito de responsabilidade criminal.",
            "§ 5º Sem prejuízo da ação que possa caber a qualquer associado, a Cooperativa, por seus dirigentes, ou representada por associado escolhido em Assembleia Geral, terá direito de ação contra os administradores, para promover a sua responsabilidade."] },
    { art: "43", txt: "{{OOrgao}} da Cooperativa poderá criar Diretoria Executiva a el{{ea}} subordinada, na qualidade de órgão estatutário composto por pessoas físicas associadas ou não, indicadas por {{aquele}} {{orgaoMin}}.",
      par: ["Parágrafo único. As funções da Administração Executiva dos negócios sociais poderão ser exercidas por técnicos contratados, segundo a estrutura que for estabelecida pel{{oa}} {{Orgao}}."] },
    { art: "44", txt: "{{OOrgao}} poderá criar comitês especiais, transitórios ou não, para estudar, planejar e coordenar a solução de questões específicas, relativas ao funcionamento da Cooperativa." },
    { sec: "SEÇÃO II", sub: "DO CONSELHO FISCAL" },
    { art: "45", txt: "A administração da Cooperativa será fiscalizada, assídua e minuciosamente, por um Conselho Fiscal, constituído de três membros efetivos e três suplentes, todos associados, eleitos anualmente pela Assembleia Geral, sendo permitida a reeleição de apenas um terço dos seus componentes.",
      par: ["§ 1º Para concorrer ao cargo de conselheiro fiscal, o associado deverá estar em pleno gozo de seus direitos, de acordo com os requisitos legais e estatutários.",
            "§ 2º Não podem fazer parte do Conselho Fiscal, além dos inelegíveis enumerados neste Estatuto, os parentes dos membros do órgão de administração, até o segundo grau, em linha reta ou colateral, bem como os parentes entre si até esse grau.",
            "§ 3º O associado não pode exercer cumulativamente cargos nos órgãos de administração e de fiscalização."] },
    { art: "46", txt: "O Conselho Fiscal reúne-se, ordinariamente, uma vez por mês e, extraordinariamente, sempre que necessário, com a participação de três dos seus membros.",
      par: ["§ 1º Em sua primeira reunião escolherá, dentre os seus membros efetivos, um Coordenador, incumbido de convocar as reuniões e dirigir os trabalhos desta, e um secretário para lavratura de atas.",
            "§ 2º As reuniões do Conselho Fiscal poderão ser convocadas, ainda, por qualquer de seus membros, por solicitação dos órgãos de administração ou da Assembleia Geral.",
            "§ 3º Na ausência do Coordenador será escolhido um substituto, na ocasião, para dirigir os trabalhos.",
            "§ 4º As deliberações serão tomadas por maioria simples de votos e constarão de ata, lavrada em livro próprio, lida, aprovada e assinada ao final dos trabalhos de cada reunião, por três membros do Conselho Fiscal presentes."] },
    { art: "47", txt: "O membro do Conselho Fiscal que, por motivo justificado, não puder comparecer à reunião, deverá comunicar o fato ao Coordenador, com antecedência mínima de {{horasAviso}} ({{horasAvisoExt}}) horas, para efeito de convocação do respectivo suplente.",
      par: ["§ 1º A comunicação deverá ser dispensada quando o suplente, devidamente notificado pelo membro efetivo, comparecer à reunião.",
            "§ 2º Quando a comunicação não ocorrer nos moldes do caput deste artigo, o Conselheiro Fiscal terá o prazo de {{diasJustif}} ({{diasJustifExt}}) dias, a contar da data em que sua ausência foi registrada, para se justificar, mediante exposição em reunião, ou em expediente do interessado ao Coordenador do Conselho Fiscal.",
            "§ 3º O Conselheiro Fiscal que faltar não poderá fazer jus ao recebimento de cédula de presença, instituída em Assembleia Geral, mesmo que a ausência seja justificada."] },
    { art: "48", txt: "Perderá o mandato o membro que faltar, injustificadamente, a {{faltasFiscConsec}} ({{faltasFiscConsecExt}}) reuniões ordinárias consecutivas ou a {{faltasFiscAno}} ({{faltasFiscAnoExt}}) reuniões durante o ano." },
    { art: "49", txt: "No caso da vacância da função de membro efetivo do Conselho Fiscal, o respectivo suplente assumirá automaticamente o lugar do titular." },
    { art: "50", txt: "No caso de ocorrerem três ou mais vagas no Conselho Fiscal, deverá haver imediata comunicação ao órgão de administração da Cooperativa, para as providências de convocação de Assembleia Geral para o devido preenchimento das vagas." },
    { art: "51", txt: "Compete ao Conselho Fiscal exercer assídua fiscalização sobre as operações, atividades e serviços da Cooperativa, examinando livros, contas e documentos, cabendo-lhe, entre outras, as seguintes atribuições:",
      inc: ["conferir, mensalmente, o saldo do numerário existente em caixa, verificando, inclusive, se o mesmo está dentro dos limites estabelecidos pelo órgão de administração;",
            "verificar se os extratos de contas bancárias conferem com a escrituração da Cooperativa;",
            "examinar se o montante das despesas e inversões realizadas está em conformidade com os planos de ação e as decisões do órgão de administração;",
            "verificar se as operações realizadas e serviços prestados correspondem em volume, qualidade e valor às conveniências econômico-financeiras da Cooperativa;",
            "certificar-se se o órgão de administração vem se reunindo regularmente, e se existem cargos vagos na sua composição;",
            "averiguar se existem reclamações dos associados quanto aos serviços prestados;",
            "inteirar-se se o recebimento dos créditos é feito com regularidade e se os compromissos sociais são atendidos com pontualidade;",
            "examinar e emitir pareceres sobre o balanço geral e demais demonstrações financeiras;",
            "averiguar se há problemas com empregados;",
            "certificar-se se há exigências ou deveres a cumprir junto a autoridades fiscais, trabalhistas ou administrativas, e, inclusive, quanto às entidades do cooperativismo;",
            "averiguar se os estoques de materiais, equipamentos e outros estão corretos, bem como se os inventários periódicos ou anuais são feitos com observância das regras próprias;",
            "examinar os balancetes e outros demonstrativos mensais, o balanço e o relatório anual do órgão de administração, emitindo parecer sobre estes para a Assembleia Geral;",
            "dar conhecimento ao órgão de administração das conclusões dos seus trabalhos, denunciando àquele órgão e à Assembleia Geral as irregularidades constatadas, convocando Assembleia Geral, se for o caso;",
            "convocar Assembleia Geral quando houver motivos graves e o órgão de administração se negar a convocá-la;",
            "propor o estabelecimento de rotinas e prazos de apresentação de balancetes, balanços, demonstrativos financeiros e prestação de contas;",
            "recomendar ao órgão de administração da Cooperativa o aprimoramento e correções necessárias ao bom desempenho nos setores contábil, financeiro e orçamentário;",
            "elaborar o seu Regimento Interno, caso seus membros julguem necessário;",
            "verificar se a Cooperativa estabelece privilégios financeiros a detentores de cargos eletivos, funcionários e terceiros; e",
            "verificar se os associados estão regularizando os compromissos assumidos na Cooperativa nos prazos convencionados."],
      par: ["§ 1º Para o desempenho de suas funções, terá o Conselho Fiscal acesso a quaisquer livros, contas e documentos, a empregados, a associados e outros, independente de autorização prévia do órgão de administração.",
            "§ 2º Poderá o Conselho Fiscal, com autorização da Assembleia Geral, contratar o necessário assessoramento técnico especializado, correndo as despesas por conta da Cooperativa."] },
    { tit: "TÍTULO V", sub: "DO BALANÇO GERAL, DESPESAS, SOBRAS, PERDAS E FUNDOS" },
    { art: "52", txt: "A apuração dos resultados do exercício social e o levantamento do balanço geral serão realizados no dia {{dataBalanco}} de cada ano." },
    { art: "53", txt: "Os resultados serão apurados segundo a natureza das operações ou serviços, pelo confronto das respectivas receitas com as despesas diretas e indiretas.",
      par: [{ opc: "rateio", quando: "proporcional", txt: "§ 1º As despesas administrativas serão rateadas na proporção das operações, sendo os respectivos montantes computados nas apurações referidas neste artigo." },
            { opc: "rateio", quando: "igual", txt: "§ 1º As despesas administrativas serão rateadas em partes iguais entre todos os associados, quer tenham ou não, no ano, usufruído dos serviços prestados pela Cooperativa." },
            "§ 2º Os resultados positivos, apurados por setor de atividade, nos termos deste artigo, serão distribuídos da seguinte forma: I – no mínimo, dez por cento ao Fundo de Reserva; e II – no mínimo, cinco por cento ao Fundo de Assistência Técnica, Educacional e Social – FATES.",
            "§ 3º As sobras líquidas apuradas no exercício, depois de deduzidos os montantes dispostos nos incisos I e II do § 2º deste artigo, serão devolvidas aos associados, proporcionalmente às operações realizadas com a Cooperativa, salvo deliberação em contrário da Assembleia Geral.",
            "§ 4º Os resultados negativos serão rateados entre os associados, na proporção das operações de cada um com a Cooperativa, se o Fundo de Reserva não for suficiente para cobri-los.",
            "§ 5º A Assembleia Geral poderá criar outros fundos, inclusive rotativos, com recursos destinados a fins específicos, fixando o modo de formação, aplicação e liquidação."] },
    { art: "54", txt: "O Fundo de Reserva destina-se a reparar as perdas do exercício e atender ao desenvolvimento das atividades, revertendo em seu favor, além do montante de dez por cento das sobras:",
      inc: ["os créditos não reclamados pelos associados, após decorridos cinco anos; e", "os auxílios e doações sem destinação especial."] },
    { art: "55", txt: "O Fundo de Assistência Técnica, Educacional e Social – FATES destina-se à prestação de serviços aos associados e seus familiares, assim como aos empregados da própria Cooperativa, podendo ser prestados mediante convênio com entidades públicas e privadas.",
      par: ["Parágrafo único. Revertem também em favor do FATES as rendas eventuais, de qualquer natureza, resultantes de operações ou atividades da Cooperativa com não associados, conforme art. 87 da Lei nº 5.764, de 1971."] },
    { art: "56", txt: "Os Fundos de Reserva e de Assistência Técnica, Educacional e Social são indivisíveis." },
    { tit: "TÍTULO VI", sub: "DA DISSOLUÇÃO E LIQUIDAÇÃO" },
    { art: "57", txt: "A Cooperativa se dissolverá de pleno direito:",
      inc: ["quando assim deliberar a Assembleia Geral, desde que os associados, totalizando o número mínimo de vinte, não se disponham a assegurar a continuidade da Cooperativa;",
            "devido à alteração de sua forma jurídica;",
            "pela redução do número de associados a menos de vinte pessoas físicas ou do capital social em patamar inferior ao mínimo, se até a Assembleia Geral subsequente, realizada em prazo não inferior a seis meses, esses quantitativos não forem restabelecidos;",
            "pela paralisação de suas atividades por mais de cento e vinte dias."] },
    { art: "58", txt: "Quando a dissolução for deliberada pela Assembleia Geral, esta nomeará um ou mais liquidantes, e um Conselho Fiscal composto por três membros para proceder à liquidação.",
      par: ["§ 1º A Assembleia Geral, nos limites de suas atribuições, pode, em qualquer época, destituir os liquidantes e os membros do Conselho Fiscal, designando seus substitutos.",
            "§ 2º O liquidante deve proceder à liquidação de conformidade com os dispositivos da Legislação Cooperativista em vigor.",
            "§ 3º O remanescente da Cooperativa, inclusive os fundos indivisíveis, depois de realizado o ativo social, pago o passivo e reembolsados os associados de suas quotas-partes, será destinado conforme legislação vigente."] },
    { art: "59", txt: "Quando a dissolução da Cooperativa não for promovida voluntariamente, nas hipóteses previstas neste Estatuto, essa medida poderá ser tomada judicialmente, a pedido de qualquer associado." },
    { tit: "TÍTULO VII", sub: "DAS DISPOSIÇÕES GERAIS E TRANSITÓRIAS" },
    { art: "60", txt: "Os casos omissos ou duvidosos serão resolvidos pela Assembleia Geral desta Cooperativa, de acordo com a Lei nº 5.764, de 1971, e os princípios doutrinários do Cooperativismo, ouvida, sempre que necessário, a {{ocb}} – OCB/{{ocbUF}}.",
      par: ["Parágrafo único. A Cooperativa somente poderá entrar em funcionamento após o registro na OCB/{{ocbUF}}, conforme determinação do art. 107 da Lei nº 5.764, de 1971."] },
    { art: "61", txt: "O processo eleitoral da Cooperativa deverá ser regulamentado por regimento específico previamente aprovado em Assembleia Geral." },
    { art: "62", txt: "A aquisição, alienação, doação ou oneração dos bens imóveis da Cooperativa dependerá de autorização {{orgaoImoveis}}, que deliberará sobre seu modo e processo de realização." },
    { art: "63", txt: "A Cooperativa poderá agir como substituta processual dos associados, em defesa de seus direitos coletivos que tenham relação com as operações de mercado que figuram como objeto da sociedade, como prevê este Estatuto, mediante autorização expressa manifestada individualmente pelo associado ou pela Assembleia Geral que delibere sobre a propositura da medida judicial, na forma do art. 88-A da Lei nº 5.764, de 1971." },
    /* ----- cláusulas padronizadas OPCIONAIS do modelo (entram só se pedidas) ----- */
    { opc: "livros", quando: "sim", art: "64", txt: "A Cooperativa deverá, além de outros, ter os seguintes livros:",
      inc: ["com termos de abertura e encerramento subscritos pelo Presidente: a) de Matrícula, com registro, em ordem cronológica, de todos os associados; b) de presença dos Associados nas Assembleias Gerais; c) de atas das Assembleias Gerais; d) de atas do órgão de Administração; e e) de atas do Conselho Fiscal;",
            "autenticados por autoridade competente: a) fiscais; e b) contábeis."],
      par: ["Parágrafo único. É facultada a adoção de livros de folhas soltas ou fichas, devidamente numeradas."] },
    { opc: "livros", quando: "sim", art: "65", txt: "No Livro de Matrícula os associados serão inscritos por ordem cronológica de admissão, dele constando:",
      inc: ["o nome, idade, estado civil, nacionalidade, profissão e residência do associado;",
            "a data de sua admissão e, quando for o caso, de sua demissão, eliminação ou exclusão; e",
            "a conta corrente das respectivas quotas-partes do capital social."] },
    { opc: "enquadramento", quando: "ME", art: "66", txt: "Os associados declaram que a cooperativa de consumo se enquadra como Microempresa – ME, nos termos da Lei Complementar nº 123, de 14 de dezembro de 2006, e que não se enquadra em qualquer das hipóteses de exclusão relacionadas no § 4º do art. 3º da mencionada lei." },
    { opc: "enquadramento", quando: "EPP", art: "66", txt: "Os associados declaram que a cooperativa de consumo se enquadra como Empresa de Pequeno Porte – EPP, nos termos da Lei Complementar nº 123, de 14 de dezembro de 2006, e que não se enquadra em qualquer das hipóteses de exclusão relacionadas no § 4º do art. 3º da mencionada lei." }
  ];

  /* ---------- ESTATUTO DE COOPERATIVA DE TRABALHO (Lei nº 12.690/2012) ----------
     O modelo da Junta é outro documento, com numeração própria e "sócio" no lugar de "associado".
     Onde o texto coincide com o geral, ele é reaproveitado por referência (função abaixo) — mas a
     numeração, os artigos exclusivos (3º, 8º, 9º, 21, 28, 37, 42) e o quorum de terceira convocação
     seguem o modelo de trabalho. */
  function trabalho() {
    var g = {};
    GERAL.forEach(function (b) { if (b.art) g[b.art] = b; });
    // troca "associado(s)" por "sócio(s)" no texto reaproveitado, como faz o modelo de trabalho
    var S = function (b, numero) {
      var c = JSON.parse(JSON.stringify(b)); c.art = numero;
      var t = function (x) { return typeof x === "string" ? x.replace(/associados/g, "sócios").replace(/associado/g, "sócio").replace(/Associados/g, "Sócios") : (x && x.txt ? (x.txt = t(x.txt), x) : x); };
      if (c.txt) c.txt = t(c.txt);
      ["inc", "al", "par"].forEach(function (k) { if (c[k]) c[k] = c[k].map(t); });
      return c;
    };
    return [
      { tit: "TÍTULO I", sub: "DAS DISPOSIÇÕES INICIAIS" },
      { cap: "CAPÍTULO I", sub: "DA DENOMINAÇÃO, SEDE, FORO, PRAZO DE DURAÇÃO, ÁREA DE AÇÃO E EXERCÍCIO SOCIAL" },
      { art: "1º", txt: "A {{denominacao}}, constituída em {{dataConstituicao}}, de acordo com a Ata da Assembleia Geral de Constituição, neste Estatuto Social designada simplesmente de Cooperativa, sociedade de pessoas, sem fins lucrativos, rege-se pelos princípios e valores do cooperativismo, por este Estatuto Social e pela legislação vigente, tendo:",
        al: ["sede, administração e foro jurídico em {{sede}}, na cidade de {{cidade}}, {{uf}};",
             "área de admissão de sócios, abrangendo {{areaAdmissao}}, podendo atuar em todo o território nacional; e",
             { opc: "prazo", quando: "indeterminado", txt: "prazo de duração indeterminado e exercício social com duração de doze meses, com início em 1º de janeiro e término em 31 de dezembro de cada ano." },
             { opc: "prazo", quando: "determinado", txt: "prazo de duração até {{prazoFim}} e exercício social com duração de {{exercicioMeses}} meses, com início em {{exercicioInicio}} e término em {{exercicioFim}} de cada ano." }] },
      { cap: "CAPÍTULO II", sub: "DO OBJETO SOCIAL" },
      { opc: "objetoTrab", quando: "producao", art: "2º", txt: "A Cooperativa, com base na colaboração recíproca a que se obrigam seus sócios, se caracteriza pela prestação direta de serviços aos associados e tem por objeto social a produção em comum de bens de {{objeto}}.",
        par: ["§ 1º A Cooperativa deterá a posse, a qualquer título, dos meios de produção dos bens para a execução do seu objeto social.",
              "§ 2º Em todos os aspectos das atividades executadas na Cooperativa devem ser rigorosamente observados os princípios da neutralidade política e da não discriminação religiosa, racial, social ou de gênero."] },
      { opc: "objetoTrab", quando: "servicos", art: "2º", txt: "A Cooperativa, com base na colaboração recíproca a que se obrigam seus sócios, se caracteriza pela prestação direta de serviços aos associados e tem por objeto social a prestação de serviços especializados a terceiros de {{objeto}}.",
        par: ["§ 1º A prestação de serviços especializados a terceiros será realizada sem a presença dos pressupostos da relação de emprego.",
              "§ 2º Em todos os aspectos das atividades executadas na Cooperativa devem ser rigorosamente observados os princípios da neutralidade política e da não discriminação religiosa, racial, social ou de gênero."] },
      { art: "3º", txt: "Quando prestadas fora do estabelecimento da Cooperativa, as atividades deverão ser submetidas a uma coordenação exercida por sócio, com mandato nunca superior a um ano ou ao prazo estipulado para a realização dessas atividades.",
        par: ["§ 1º A eleição do coordenador será realizada entre os sócios que se disponham a realizar as atividades, em reunião específica que tratará sobre os requisitos para sua consecução, os valores contratados e a retribuição pecuniária de cada sócio partícipe.",
              "§ 2º As atividades, tarefas, atribuições e responsabilidades do Coordenador poderão ser disciplinadas em forma de Resoluções, Regulamentos ou Instruções que, em seu conjunto, constituirão o Regimento Interno da Cooperativa."] },
      { tit: "TÍTULO II", sub: "DOS ASSOCIADOS" },
      { cap: "CAPÍTULO I", sub: "DAS CONDIÇÕES DE ADMISSÃO" },
      { art: "4º", txt: "Podem se associar à Cooperativa {{admissaoQuem}}, desde que adiram aos propósitos sociais e preencham as condições estabelecidas neste Estatuto, salvo se houver impossibilidade técnica de prestação de serviços pela Cooperativa.",
        par: ["§ 1º A admissão de sócios na Cooperativa é limitada consoante as possibilidades de reunião, abrangência das operações, controle e prestação de serviços e congruente com o objeto deste Estatuto Social.",
              "§ 2º Poderão ingressar na Cooperativa, excepcionalmente, pessoas jurídicas que tenham por objeto as mesmas ou correlatas atividades econômicas das pessoas físicas ou, ainda, aquelas sem fins lucrativos, desde que satisfaçam as condições estabelecidas neste Estatuto Social.",
              "§ 3º Não podem ingressar no quadro da Cooperativa os agentes de comércio e empresários que operem no mesmo campo econômico da sociedade.",
              "§ 4º A representação da pessoa jurídica junto à Cooperativa se fará por meio de pessoa física especialmente designada, mediante instrumento específico que, nos casos em que houver mais de um representante, identificará os poderes de cada um."] },
      { art: "5º", txt: "O número de sócios será ilimitado quanto ao máximo, não podendo ser inferior a sete pessoas físicas." },
      S(g["5º"], "6º"),
      { cap: "CAPÍTULO II", sub: "DOS DIREITOS" },
      { art: "7º", txt: "São direitos do sócio, além de outros que a Assembleia Geral venha a instituir:",
        inc: ["retiradas não inferiores ao piso da categoria profissional e, na ausência deste, não inferiores ao salário mínimo, calculadas de forma proporcional às horas trabalhadas ou às atividades desenvolvidas;",
              "duração do trabalho normal não superior a oito horas diárias e quarenta e quatro horas semanais;",
              "repouso semanal remunerado, preferencialmente aos domingos;",
              "repouso anual remunerado;",
              "retirada para o trabalho noturno superior à do diurno;",
              "adicional sobre a retirada para as atividades insalubres ou perigosas;",
              "seguro de acidente de trabalho;",
              "ser convocado para as Assembleias Gerais, discutir e votar os assuntos que nelas forem tratados, ressalvadas as disposições legais e estatutárias;",
              "ser votado para os cargos sociais, desde que atendidas as disposições legais e regulamentares pertinentes;",
              "exercer qualquer atividade da Cooperativa, conforme deliberado em Assembleia Geral;",
              "propor medidas que julgar convenientes aos interesses da Cooperativa;",
              "examinar, mediante pedido formal prévio, informações e documentos relativos às atividades, aos negócios e à administração da Cooperativa;",
              "receber devolução do capital integralizado, juros e sobras, nos termos deste Estatuto Social;",
              "tomar conhecimento dos normativos da Cooperativa;",
              "demitir-se da Cooperativa quando lhe convier, obedecidas as disposições aplicáveis deste Estatuto Social."],
        par: ["§ 1º Na ausência do piso da categoria profissional ou do piso salarial regional, será considerado o salário mínimo.",
              "§ 2º A duração do trabalho dos sócios deverá observar o disposto nas normas de saúde, segurança e medicina do trabalho.",
              "§ 3º A Assembleia Geral poderá prever jornada especial, em regime de plantão ou escala, para o sócio quando a atividade, por sua natureza, assim o demandar, facultada a compensação de horários.",
              "§ 4º O disposto no § 3º deste artigo não prejudica a aplicação de regime diferenciado de duração do trabalho, quando previsto em norma específica.",
              "§ 5º A Cooperativa deverá fixar, em Assembleia Geral, as regras de funcionamento da sociedade e a forma de execução dos trabalhos.",
              "§ 6º A fim de serem apreciadas pela Assembleia Geral, as propostas dos sócios, referidas neste Estatuto, deverão ser previamente apresentadas ao órgão de administração e constar do respectivo Edital de Convocação."] },
      { art: "8º", txt: "Não se aplica o disposto nos incisos III e IV do caput do art. 7º nos casos em que as operações entre o sócio e a Cooperativa sejam eventuais, salvo decisão assemblear em contrário (§ 1º do art. 7º da Lei nº 12.690, de 2012).",
        par: ["Parágrafo único. Consideram-se operações eventuais entre o sócio e a Cooperativa aquelas que se desenvolvam de maneira ocasional e descontinuada, conforme parâmetros definidos em Assembleia Geral."] },
      { art: "9º", txt: "A Cooperativa buscará meios, inclusive mediante provisionamento de recursos, com base em critérios que devem ser aprovados em Assembleia Geral, para assegurar os direitos previstos nos incisos I, III, IV, V, VI e VII do caput do art. 7º e outros que a Assembleia Geral venha a instituir (§ 2º do art. 7º da Lei nº 12.690, de 2012)." },
      { cap: "CAPÍTULO III", sub: "DOS DEVERES" },
      { art: "10", txt: "São deveres dos sócios:",
        inc: ["satisfazer, pontualmente, os compromissos que contrair com a Cooperativa;",
              "realizar com a Cooperativa as operações econômicas que constituam sua finalidade;",
              "integralizar as quotas-partes do capital subscritas, nos termos deste Estatuto Social;",
              "cobrir as perdas do exercício, quando houver, proporcionalmente às operações que realizou com a Cooperativa, se o Fundo de Reserva não for suficiente para cobri-las;",
              "arcar, na proporção direta da fruição de serviços prestados pela Cooperativa, com a cobertura das despesas da sociedade, bem como das taxas de serviço e encargos operacionais que forem estabelecidos;",
              "cumprir as disposições da lei e deste Estatuto Social, as deliberações das Assembleias Gerais, do órgão de administração{{,daDiretoriaExecutiva}}, bem como de outros instrumentos de normatização destinados direta ou indiretamente aos sócios;",
              "zelar pelos interesses morais, éticos, sociais e materiais da Cooperativa;",
              "prestar, quando solicitado, esclarecimentos sobre as suas atividades à Cooperativa;",
              "manter suas informações cadastrais atualizadas junto à Cooperativa;",
              "comunicar, sem a necessidade de se identificar, situações com indícios de ilicitude de qualquer natureza, relacionadas à Cooperativa;",
              "observar as normas de saúde e segurança do trabalho previstas na legislação em vigor e em atos normativos expedidos pelas autoridades competentes; e",
              "participar das Assembleias Gerais, discutir e votar os assuntos que nelas forem tratados, ressalvadas as disposições legais e estatutárias."] },
      { cap: "CAPÍTULO IV", sub: "DAS HIPÓTESES DE DESLIGAMENTO DE SÓCIOS" },
      { sec: "SEÇÃO I", sub: "DA DEMISSÃO" }, S(g["8º"], "11"),
      { sec: "SEÇÃO II", sub: "DA ELIMINAÇÃO" }, S(g["9º"], "12"), S(g["10"], "13"),
      { sec: "SEÇÃO III", sub: "DA EXCLUSÃO" }, S(g["11"], "14"),
      { sec: "SEÇÃO IV", sub: "DISPOSIÇÕES GERAIS" }, S(g["12"], "15"),
      { cap: "CAPÍTULO V", sub: "DAS RESPONSABILIDADES" },
      { opc: "responsabilidade", quando: "limitada", art: "16", txt: "O sócio responde pelos compromissos da Cooperativa limitado ao valor do capital por ele subscrito e o montante das perdas que lhe couber.",
        par: ["Parágrafo único. A responsabilidade do sócio para com terceiros, como membro da sociedade, somente poderá ser invocada depois de judicialmente exigida da Cooperativa."] },
      { opc: "responsabilidade", quando: "ilimitada", art: "16", txt: "O sócio responde por todos os compromissos da Cooperativa, de forma pessoal, solidária e independente do valor do capital por ele subscrito.",
        par: ["Parágrafo único. A responsabilidade do sócio para com terceiros, como membro da sociedade, somente poderá ser invocada depois de judicialmente exigida da Cooperativa."] },
      S(g["14"], "17"),
      { tit: "TÍTULO III", sub: "DO CAPITAL SOCIAL" },
      S(g["15"], "18"), S(g["16"], "19"), S(g["17"], "20"),
      { art: "21", txt: "É vedado à Cooperativa distribuir verbas de qualquer natureza entre os sócios, exceto a retirada devida em razão do exercício de sua atividade como sócio ou retribuição por conta de reembolso de despesas comprovadamente realizadas em proveito da Cooperativa." },
      { tit: "TÍTULO IV", sub: "DOS ÓRGÃOS SOCIAIS" },
      { cap: "CAPÍTULO I", sub: "DA ASSEMBLEIA GERAL" },
      S(g["18"], "22"), S(g["19"], "23"), S(g["20"], "24"),
      { art: "25", txt: "O quorum mínimo para instalação da Assembleia Geral será:",
        inc: ["dois terços do número de sócios, em primeira convocação;",
              "metade mais um dos sócios, em segunda convocação; e",
              "cinquenta associados, ou, no mínimo, vinte por cento do total de sócios, prevalecendo o menor número, em terceira convocação, exigida a presença de, no mínimo, quatro sócios, para as cooperativas que possuam até dezenove sócios matriculados."],
        par: ["§ 1º Para efeito de verificação do quorum de que trata este artigo, o número de sócios presentes, em cada convocação, será contado por suas assinaturas apostas no Livro de Presença, seguidas do respectivo número de matrícula.",
              "§ 2º Constatada a existência de quorum no horário estabelecido no Edital de Convocação, o Presidente instalará a Assembleia, com a declaração do número de sócios presentes, e fará transcrever estes dados para a respectiva ata."] },
      S(g["22"], "26"),
      { art: "27", txt: "Dos editais de convocação das Assembleias Gerais deverão constar:",
        inc: ["a denominação da Cooperativa e o número de Cadastro Nacional de Pessoas Jurídicas – CNPJ, seguidos da expressão “Convocação da Assembleia Geral Ordinária, Extraordinária ou Especial”, conforme o caso;",
              "o dia e a hora da reunião, em cada convocação, assim como o local da sua realização, o qual, salvo motivo justificado, será o da sede social;",
              "a sequência ordinal das convocações;",
              "a ordem do dia dos trabalhos, com as devidas especificações e, em caso de reforma do Estatuto Social, a indicação precisa da matéria;",
              "o número de sócios existentes na data de sua expedição, para efeito do cálculo do quorum de instalação; e",
              "a data e assinatura do responsável pela convocação."],
        par: ["§ 1º No caso de a convocação ser feita por sócios, o edital será assinado, no mínimo, por um quinto dos sócios em pleno gozo dos seus direitos."] },
      { art: "28", txt: "A notificação dos sócios para participação das assembleias será pessoal e ocorrerá com antecedência mínima de dez dias de sua realização, com declaração de ciência do sócio, devidamente datada, no ato da comunicação.",
        par: ["§ 1º Na impossibilidade de notificação pessoal, a notificação será realizada via postal, com Aviso de Recebimento – AR, respeitada a antecedência prevista no caput deste artigo.",
              "§ 2º Na impossibilidade de realização das notificações anteriores, os sócios serão notificados mediante edital afixado na sede{{,outrosLocaisEdital}} e publicado em jornal de grande circulação na região da sede da Cooperativa ou na região onde ela exerça suas atividades, respeitada a antecedência prevista no caput deste artigo."] },
      S(g["24"], "29"), S(g["25"], "30"), S(g["26"], "31"), S(g["27"], "32"), S(g["28"], "33"), S(g["29"], "34"),
      { art: "35", txt: "As deliberações nas Assembleias Gerais serão consideradas válidas quando contarem com a aprovação da maioria absoluta dos sócios presentes, tendo cada sócio direito a um só voto, qualquer que seja o número de suas quotas-partes.",
        par: ["§ 1º Em regra, a votação será a descoberto, mas a Assembleia Geral poderá optar pelo voto secreto.",
              "§ 2º Não será permitida a representação de sócio por meio de mandatário."] },
      S(g["31"], "36"),
      { art: "37", txt: "A Cooperativa deverá estabelecer incentivos à participação efetiva dos sócios na Assembleia Geral e eventuais sanções em caso de ausências injustificadas." },
      S(g["32"], "38"),
      { sec: "SEÇÃO I", sub: "DA ASSEMBLEIA GERAL ORDINÁRIA" },
      { art: "39", txt: "A Assembleia Geral Ordinária será realizada obrigatoriamente uma vez por ano, no decorrer dos três primeiros meses após o término do exercício social, e deliberará sobre os seguintes assuntos, que deverão constar da ordem do dia:",
        inc: ["prestação de contas dos órgãos de administração, acompanhada do parecer do Conselho Fiscal, compreendendo: a) relatório da gestão; b) balanço; c) demonstrativo das sobras apuradas ou das perdas decorrentes da insuficiência das contribuições para cobertura das despesas da sociedade e o parecer do Conselho Fiscal; e d) plano de atividades da Cooperativa para o exercício seguinte;",
              "destinação das sobras apuradas ou o rateio das perdas, deduzindo-se, no primeiro caso, as parcelas para os fundos obrigatórios;",
              "eleição e posse dos componentes dos órgãos de administração e de outros órgãos necessários à administração, quando for o caso;",
              "eleição e posse dos componentes do Conselho Fiscal e de outros, quando for o caso;",
              "quando previsto, a fixação do valor dos honorários, gratificações e cédula de presença dos membros dos órgãos de administração e do Conselho Fiscal;",
              "adoção ou não de diferentes faixas de retirada dos sócios;",
              "quaisquer assuntos de interesse social, excluídos aqueles de competência exclusiva da Assembleia Geral Extraordinária enumerados neste Estatuto Social."],
        par: ["§ 1º Os membros dos órgãos de administração e fiscalização não poderão participar da votação das matérias referidas nos incisos I (exceto alínea “d”) e V deste artigo.",
              "§ 2º A aprovação do relatório, balanço e contas dos órgãos de administração não desonera seus componentes da responsabilidade por erro, dolo, fraude ou simulação, bem como por infração da lei ou deste Estatuto Social.",
              "§ 3º No caso de fixação de faixas de retirada, a Assembleia Geral deverá fixar a diferença entre as de maior e as de menor valor."] },
      { sec: "SEÇÃO II", sub: "DA ASSEMBLEIA GERAL EXTRAORDINÁRIA" },
      S(g["34"], "40"),
      { art: "41", txt: "É da competência exclusiva da Assembleia Geral Extraordinária deliberar sobre os seguintes assuntos:",
        inc: ["reforma do Estatuto;", "fusão, incorporação ou desmembramento;", "mudança de objeto da sociedade;", "dissolução voluntária da sociedade e nomeação de liquidantes;", "contas do liquidante; e",
              "carência da fruição dos direitos de retiradas e seguro de acidente de trabalho previstos no art. 7º deste Estatuto Social."],
        par: ["Parágrafo único. São necessários os votos de dois terços dos sócios presentes para tornar válidas as deliberações de que trata este artigo."] },
      { sec: "SEÇÃO III", sub: "DA ASSEMBLEIA GERAL ESPECIAL" },
      { art: "42", txt: "Será realizada no segundo semestre de todo ano, no mínimo, uma Assembleia Geral Especial para deliberar, entre outros especificados no edital de convocação, sobre os seguintes assuntos:",
        inc: ["gestão da Cooperativa;", "disciplina, direitos e deveres dos sócios;", "planejamento e resultado econômico dos projetos;", "contratos firmados; e", "organização do trabalho."] },
      { cap: "CAPÍTULO II", sub: "DA ADMINISTRAÇÃO" },
      { opc: "orgao", quando: "conselho", sec: "SEÇÃO I", sub: "DO CONSELHO DE ADMINISTRAÇÃO" },
      { opc: "orgao", quando: "diretoria", sec: "SEÇÃO I", sub: "DA DIRETORIA" },
      { art: "43", txt: "{{OOrgao}} é o órgão superior na hierarquia administrativa, sendo de sua competência e responsabilidade a decisão sobre todo e qualquer assunto de ordem econômica e social, de interesse da Cooperativa ou de seus sócios, nos termos da lei, deste Estatuto Social e das recomendações da Assembleia Geral." },
      { art: "44", txt: "{{OOrgao}} será compost{{oa}} de {{nOrgao}} ({{nOrgaoExt}}) membros, sendo um Presidente e {{cargosOrgao}}, todos sócios no gozo de seus direitos sociais, eleitos pela Assembleia Geral para mandato de {{mandato}} ({{mandatoExt}}) anos, sendo obrigatória, ao término de cada mandato, a renovação de, no mínimo, um terço dos seus componentes.",
        par: ["§ 1º Não podem fazer parte d{{oa}} {{Orgao}}, além das pessoas impedidas por lei, os condenados a pena que vede, ainda que temporariamente, o acesso a cargos públicos; ou por crime falimentar, de prevaricação, peita ou suborno, concussão, peculato, ou contra a economia popular, a fé pública ou a propriedade.",
              "§ 2º Não podem compor {{oa}} mesm{{oa}} {{Orgao}} os parentes entre si até segundo grau, em linha reta ou colateral."] },
      S(g["38"], "45"), S(g["39"], "46"), S(g["40"], "47"), S(g["41"], "48"), S(g["42"], "49"), S(g["43"], "50"), S(g["44"], "51"),
      { sec: "SEÇÃO II", sub: "DO CONSELHO FISCAL" },
      { opc: "fiscal", quando: "completo", art: "52", txt: "A administração da Cooperativa será fiscalizada, assídua e minuciosamente, por um Conselho Fiscal, constituído de três membros efetivos e três suplentes, todos sócios, eleitos anualmente pela Assembleia Geral, sendo permitida a reeleição de apenas um terço dos seus componentes.",
        par: ["§ 1º Para concorrer ao cargo de conselheiro fiscal, o sócio deverá estar em pleno gozo de seus direitos, de acordo com os requisitos legais e estatutários.",
              "§ 2º Não podem fazer parte do Conselho Fiscal, além dos inelegíveis enumerados neste Estatuto, os parentes dos membros do órgão de administração, até o segundo grau, em linha reta ou colateral, bem como os parentes entre si até esse grau.",
              "§ 3º O sócio não pode exercer cumulativamente cargos nos órgãos de administração e de fiscalização."] },
      { opc: "fiscal", quando: "reduzido", art: "52", txt: "A administração da Cooperativa será fiscalizada, assídua e minuciosamente, por um Conselho Fiscal, constituído de três membros efetivos, todos sócios, eleitos anualmente pela Assembleia Geral, sendo permitida a reeleição de apenas um terço dos seus componentes.",
        par: ["§ 1º Para concorrer ao cargo de conselheiro fiscal, o sócio deverá estar em pleno gozo de seus direitos, de acordo com os requisitos legais e estatutários.",
              "§ 2º Não podem fazer parte do Conselho Fiscal, além dos inelegíveis enumerados neste Estatuto, os parentes dos membros do órgão de administração, até o segundo grau, em linha reta ou colateral, bem como os parentes entre si até esse grau.",
              "§ 3º O sócio não pode exercer cumulativamente cargos nos órgãos de administração e de fiscalização."] },
      S(g["46"], "53"), S(g["47"], "54"), S(g["48"], "55"), S(g["49"], "56"), S(g["50"], "57"),
      (function () { var c = S(g["51"], "58"); c.par[1] = "§ 2º Poderá o Conselho Fiscal, com anuência do órgão de administração e com autorização da Assembleia Geral, contratar o necessário assessoramento técnico especializado, correndo as despesas por conta da Cooperativa."; return c; })(),
      { tit: "TÍTULO V", sub: "DO BALANÇO GERAL, DESPESAS, SOBRAS, PERDAS E FUNDOS" },
      S(g["52"], "59"), S(g["53"], "60"), S(g["54"], "61"), S(g["55"], "62"), S(g["56"], "63"),
      { tit: "TÍTULO VI", sub: "DA DISSOLUÇÃO E LIQUIDAÇÃO" },
      { art: "64", txt: "A Cooperativa se dissolverá de pleno direito:",
        inc: ["quando assim deliberar a Assembleia Geral, desde que os sócios, totalizando o número mínimo de sete, não se disponham a assegurar a continuidade da Cooperativa;",
              "devido à alteração de sua forma jurídica;",
              "pela redução do número de sócios a menos de sete pessoas físicas ou do capital social em patamar inferior ao mínimo, se até a Assembleia Geral subsequente, realizada em prazo não inferior a seis meses, esses quantitativos não forem restabelecidos; e",
              "pela paralisação de suas atividades por mais de cento e vinte dias."] },
      S(g["58"], "65"), S(g["59"], "66"),
      { tit: "TÍTULO VII", sub: "DAS DISPOSIÇÕES GERAIS E TRANSITÓRIAS" },
      { art: "67", txt: "Os casos omissos ou duvidosos serão resolvidos pela Assembleia Geral desta Cooperativa, de acordo com a Lei nº 12.690, de 2012, e, no que com ela não colidir, pelas Leis nº 5.764, de 1971, e 10.406, de 2002 – Código Civil, e pelos princípios doutrinários do Cooperativismo, ouvida, sempre que necessário, a {{ocb}} – OCB/{{ocbUF}}.",
        par: ["Parágrafo único. A Cooperativa somente poderá entrar em funcionamento após o registro na OCB/{{ocbUF}}, conforme determinação do art. 107 da Lei nº 5.764, de 1971."] },
      { art: "68", txt: "O processo eleitoral da Cooperativa deverá ser regulamentado por regimento específico previamente aprovado em Assembleia Geral.",
        par: ["Parágrafo único. Fica inelegível para qualquer cargo na Cooperativa, pelo período de até cinco anos, contado a partir da sentença transitada em julgado, o sócio, dirigente ou administrador condenado pela prática das fraudes elencadas no art. 18 da Lei nº 12.690, de 2012."] },
      S(g["62"], "69"), S(g["63"], "70"),
      (function () { var c = S(g["64"], "71"); return c; })(),
      (function () { var c = S(g["65"], "72"); return c; })()
    ];
  }

  window.MODELOS_COOP = {
    geral: { titulo: "ESTATUTO SOCIAL DE COOPERATIVA", lei: "Lei nº 5.764, de 16 de dezembro de 1971", minimo: 20, blocos: GERAL },
    trabalho: { titulo: "ESTATUTO SOCIAL DA COOPERATIVA DE TRABALHO", lei: "Lei nº 12.690, de 19 de julho de 2012", minimo: 7, blocos: trabalho() }
  };
})();
